<a href="https://colab.research.google.com/github/ghdakrk/computr_vision/blob/main/perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

class Neuron:
    ''' 간단한 전방 전달 인공 뉴런.
    Args:
        num_input (int): 입력벡터 크기 / 입력값 개수.
        activation_fn (callable): 활성화 함수.
    Attributes:
        W (ndarray): 각 입력에 대한 가중치
        b (float): 편향값, 가중하베 더해짐
        activation_fn (callable): 활성화 함수.
    '''

    def __init__(self, num_inputs, activation_fn):
        # 랜덤값으로 가중치 벡터와 편향값을 초기화함:
        self.W = np.random.rand(num_inputs)
        self.b = np.random.rand(1)
        self.activation_fn = activation_fn

    def forward(self, x):
        '''뉴런을 통해 입력 신호를 전달.'''
        z = np.dot(x, self.W) + self.b
        return self.activation_fn(z)

In [10]:
# 결과를 복제할 수 있도록 랜덤 숫자 생성기의 시드값을 고정
np.random.seed(42)
# 3개의 랜덤 입력을 칼럼으로 받을 수 있는 배열 (shape = `(1, 3)`)
x = np.random.rand(3).reshape(1, 3) 
# array([[0.37454012, 0.95071431, 0.73199394]])

# 퍼셉트론을 인스턴스화(계단 함수를 사용하는 간단한 뉴런)
step_fn = lambda y: 0 if y <= 0 else 1
perceptron = Neuron(num_inputs=x.size, activation_fn=step_fn)
out = perceptron.forward(x)
out

1

1

In [12]:
class FullyConnectedLayer:
    ''' 간단한 전방 전달 인공 뉴런.
    Args:
        num_input (int): 입력벡터 크기 / 입력값 개수.
        layer_size (int): 출력 벡터의 크기 / 뉴런의 개수.
        activation_fn (callable): 활성화 함수.
    Attributes:
        W (ndarray): 각 입력에 대한 가중치
        b (float): 편향값, 가중하베 더해짐
        size (int): 계층의크기 / 뉴런의 개수
        activation_fn (callable): 활성화 함수.
    '''

    def __init__(self, num_inputs, layer_size, activation_fn):
        # 랜덤값으로 가중치 벡터와 편향값을 초기화함:
        self.W = np.random.standard_normal((num_inputs, layer_size))
        self.b = np.random.standard_normal(layer_size)
        self.size = layer_size
        self.activation_fn = activation_fn

    def forward(self, x):
        '''뉴런을 통해 입력 신호를 전달.'''
        z = np.dot(x, self.W) + self.b
        return self.activation_fn(z)

In [17]:
np.random.seed(42)
# 2개의 값을 갖는 램덤 입력 칼럼 벡터 (shape = `(1,2)`):
x1 = np.random.uniform(-1, 1, 2).reshape(1, 2)
x2 = np.random.uniform(-1, 1, 2).reshape(1, 2)

relu_fn = lambda y: np.maximum(y, 0)
layer = FullyConnectedLayer(2, 3, relu_fn)

out1 = layer.forward(x1)
out2 = layer.forward(x2)
x12 = np.concatenate((x1,x2))
out12 = layer.forward(x12)

out12

array([[0.28712364, 0.        , 0.33478571],
       [0.        , 0.        , 1.08175419]])

In [16]:
np.random.uniform(-1, 1, 2)

array([-0.68796272, -0.68801096])